name: level_editor
description: "A level editor which can be embedded into existing games."
version: 0.0.1
homepage: https://www.github.com/chrisnorman7/level_editor

environment:
  sdk: ^3.6.0-334.3.beta
  flutter: ">=1.17.0"

dependencies:
  backstreets_widgets: ^0.24.1
  flutter:
    sdk: flutter
  flutter_audio_games: ^0.32.0
  flutter_riverpod: ^2.6.1
  flutter_soloud: ^2.1.7
  json_annotation: ^4.9.0
  path: ^1.9.0
  recase: ^4.1.0
  riverpod_annotation: ^2.6.1
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  riverpod_generator: ^2.6.2
  riverpod_lint: ^2.6.2
